title: Folorunsho Adigun
logo: Profile pic.jpeg
description: I am a highly motivated and efficient data analyst and business intelligence analyst with experience in database queries, data validation, statistical data analysis, and data modelling to enhance business operational performance. I have worked extensively with Excel for report automation, Charts, Pivot tables, what-if analysis, SQL for data interrogation and manipulation, and Power BI for data integration, data transformation, and data visualization for clinical, commercial, and financial analysis.
#google_analytics:
theme: jekyll-theme-minimal
